CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  uid TEXT UNIQUE NOT NULL,
  reg_date TEXT NOT NULL,
  is_admin BOOLEAN DEFAULT 0,
  is_blocked BOOLEAN DEFAULT 0
);

CREATE TABLE activation_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key TEXT UNIQUE NOT NULL,
  duration TEXT NOT NULL, -- '30', '365', 'forever'
  used BOOLEAN DEFAULT 0
);

CREATE TABLE purchases (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  product TEXT NOT NULL,
  purchase_date TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
